---
title: "Installing metablastr and all sequence search tools"
author: "Hajk-Georg Drost"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Install sequence search tools used by `metablastr`

We recommend using the `Conda`, `Miniconda` or `Bioconda` infrastructure to load and install
all search tools, because it will automatically resolve version conflicts and will
make your life much easier.


## Miniconda, Conda, and Bioconda

### Installing Miniconda (a small version of Anaconda)

To install conda and bioconda users first need to [install Miniconda](https://conda.io/miniconda.html).

#### Install on Linux

```
# download installation script
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
# run installation script
bash Miniconda3-latest-Linux-x86_64.sh
```

Follow the following procedures:

The installer prompts “In order to continue the installation process, please review the license agreement.” Click Enter to view license terms.

Scroll to the bottom of the license terms and enter “Yes” to agree.

The installer prompts you to click Enter to accept the default install location, CTRL-C to cancel the installation, or specify an alternate installation directory. If you accept the default install location, the installer displays “PREFIX=/home/<user>/anaconda<2 or 3>” and continues the installation. It may take a few minutes to complete.

The installer prompts “Do you wish the installer to prepend the Anaconda<2 or 3> install location to PATH in your `/home/<user>/.bashrc ?`” Enter Yes.

NOTE: If you enter “No”, you must manually add the path to Anaconda or conda will not work. See FAQ.

The installer describes Microsoft VS Code and asks if you would like to install VS Code. Enter yes or no. If you selected yes, follow the instructions on screen to complete the VS Code installation.

NOTE: Installing VS Code with the Anaconda installer requires an internet connection. Offline users may be able to find an offline VS Code installer from Microsoft.

The installer finishes and displays “Thank you for installing Anaconda<2 or 3>!”

Close and open your terminal window for the installation to take effect, or you can enter the command source `/home/<user>/.bashrc`.

Details here: http://docs.anaconda.com/anaconda/install/linux/

See also issue here: https://github.com/scrapy/scrapy/issues/3141#issuecomment-368690842

Now users can type `conda` in the command line.
E.g.

```
conda update conda
```

Next run to update user rights:

```sh
sudo chown -R <user>:<user> /usr/local/miniconda3
```

### Using Conda

Install packages like this (`conda intsall [...]`):

```
conda install numpy
```

Or search for available packages like this:

```
conda search PACKAGENAME
```

Learn more by [Getting Started with Conda](https://conda.io/docs/user-guide/getting-started.html)
and [download the conda cheatsheet](https://conda.io/docs/user-guide/cheatsheet.html).

Here are the full [Conda Docs](https://conda.io/docs/).

### Installing Bioconda

Here are the detailed [Bioconda installation instructions](https://bioconda.github.io/).

```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```

After installing conda you will need to add the bioconda channel as well as the other channels bioconda depends on. It is important to add them in this order so that the priority is set correctly (that is, conda-forge is highest priority).

The conda-forge channel contains many general-purpose packages not already found in the defaults channel.


## Installing search tools using Bioconda

Now users can downlaod and istall the search tools as follows:

```
conda install -c bioconda blast diamond ac-diamond mmseqs2 last
conda install -c ostrokach-forge hh-suite
```

